#!/bin/bash
echo -n "Clang..."
find Xilinx/SDK/alpha_live.sdk \( -iname \*.c -o -iname \*.h -o -iname \*.cpp \) -not -path '*_bsp/*' | xargs clang-format-5.0 -style=file -i
#find . \( -iname \*.c -o -iname \*.h -o -iname \*.cpp \) -not -path '*_bsp/*' | xargs clang-format-5.0 -style=file -i
echo -n "BANG!"
