#!/bin/bash
grep --color=auto -R -I -n --include "CMakeLists.txt" --include "Jenkinsfile" --include "*.c" --include "*.cpp" --include "*.cl" --include "*.hpp" --include "*.h" --include "*.asm" --include "*.py" --include "*.sv" --include "*.svh" --exclude "*Vtt*" --exclude-dir "*bsp*" --exclude-dir "*Vtt*" --exclude-dir "third_party" --exclude-dir "obj" --exclude-dir "bin" "$@"
