#!/bin/bash
if [ -n "$@" ]; then
	THUMBDIR="$1/.thumbs"
	mkdir "$THUMBDIR"
	for i in "$1"/*.jpg
	do
		djpeg "$i" | pnmscale -xysize 200 150 | cjpeg -opti -progr -qual '75%' > "$THUMBDIR"/`basename "$i"`
		echo "$i processed"
	done
else
	echo "I need an argument"
	exit 3
fi
