#!/bin/bash

if [ $# -ne 0 ]; then
	#A set of parameters was passed to the script.
	#Save them for next time in a script at ~/.$SCRIPTNAME
	ssh -X mphansen@$1.mathlab.mtu.edu
else
	ssh -X mphansen@galois3.mathlab.mtu.edu
fi

