#!/bin/bash
SET_TITLE="Picozed-Build" gnome-terminal --working-directory="/home/matt/git/phalanx-picozed" 
SET_TITLE="Picozed-Git"   gnome-terminal --working-directory="/home/matt/git/phalanx-picozed" 
SET_TITLE="Picozed-Vim"   gnome-terminal --working-directory="/home/matt/git/phalanx-picozed/Xilinx/SDK/alpha_live.sdk"
SET_TITLE="SAM-Git"       gnome-terminal --working-directory="/home/matt/git/ATSAM-BB1-Harmony" 
SET_TITLE="SAM-Vim"       gnome-terminal --working-directory="/home/matt/git/ATSAM-BB1-Harmony"
