#!/bin/bash
echo "SECONDS, PUMP_TEC_STATE, PUMP_TEC_%, PUMP_TEMP, PUMP_DRV_I_SENSE, SEED_TEC_STATE, SEED_TEC_%, SEED_TEMP, SEED_TEMP_V, BOARD_TEMP, CASE_TEMP, POWER_RAW, POWER_MW"
sed "s/^.*\[//g" "$@" | sed "/^[^0123456789].*$/d" | sed "s/\]//g" | sed "/PUMP/d" | sed "s/ A /   /g" | sed "s/ C /   /g" | sed "s/ V /   /g" | sed "s/%/ /g" | sed "s/ C[^O]/  /g" | sed "s/HEAT/HEAT          /g" | sed "s/COOL/COOL          /g" | sed "s/IDLE/IDLE          /g" | sed "s/mW/ /g" | sed "s/  [ ]*/,/g"
